version: '3'
services:
  app_go:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGOURI: mongodb+srv://pasamandev:pasamandev@cluster0.mudgo.mongodb.net/?retryWrites=true&w=majority
    ports:
      - 6000:6000
    restart: on-failure